---

- name: "{{ jboss_eap_instance_name }} (05) Copy service systemd unit file"
  template:
    owner: "{{ jboss.user }}"
    group: "{{ jboss.group }}"
    src: jboss-as-standalone.service.j2
    dest: "/etc/systemd/system/{{ jboss_eap_instance_service_name }}.service"
    mode: "0750"
  register: conf_service

- name: "{{ jboss_eap_instance_service_name }} (05) Enable jboss service"
  systemd:
    name: "{{ jboss_eap_instance_service_name }}.service"
    enabled: yes

# Reloading systemd. Should be executed here and not as a handler.
- name: "{{ jboss_eap_instance_service_name }} (05) Reload systemd"
  systemd:
    name: "jboss_{{ jboss_eap_instance_service_name }}.service"
    daemon_reload: yes

- name: "{{ jboss_eap_instance_name }} (05) Execute CLI file(s)"
  become_user: "{{ jboss.user }}"
  shell: 'sleep 10; {{ jboss_home }}/bin/jboss-cli.sh --controller=127.0.0.1:9990 -c --file="{{ jboss_eap_instance_dir }}/configuration/{{ item | basename }}"'
  with_items: "{{ cli_list }}"
  ignore_errors: yes
  register: cli_result

- name: Output CLI execution
  debug: var={{ item }}
  with_items: cli_result.results

- name: "{{ jboss_eap_instance_name }} (05) Stop faulty instances"
  when: conf_11.changed and cli_result.failed is defined and cli_result.failed
  become_user: "{{ jboss.user }}"
  ignore_errors: yes
  shell: 'pkill -TERM -f "^java(.*){{ jboss_eap_instance_dir }}"'

- name: "{{ jboss_eap_instance_name }} (05) Failure"
  when: conf_11.changed and cli_result.failed is defined and cli_result.failed
  fail: msg="One of the CLI commands failed."

- name: "{{ jboss_eap_instance_name }} (05) Ensure JBoss EAP is running"
  service:
    name: "{{ jboss_eap_instance_service_name }}"
    state: started
    enabled: yes
